version: "3"
services:
  postgresql:
    image: postgres:9.5-alpine
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - ./.postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: 
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
